<?php

/**
 * @desc TypePHP 基础插件配置文件
 * @author Tinywan(ShaoBo Wan)
 * @date 2026/09/05
 */
declare(strict_types=1);

return [
    'enable' => true,
    // Docker 编译环境配置
    'docker' => [
        'enabled' => true,
        'image' => 'tinywan/typephp-webman-builder:v0.1.3',
    ],
    // 默认输出配置
    'build' => [
        'output_name' => 'webman-server',
        'dist_dir' => 'dist',
        'clean_build' => true,
        // Large projects may need 1 to cap the extension translation unit's memory peak.
        'jobs' => 4,
    ],
    // 编译排除但运行时按原相对路径随包的动态数据、模板和静态资源。
    'runtime_resources' => [
        'vendor/laravel/serializable-closure',
        'vendor/phpmailer/phpmailer/get_oauth_token.php',
        'vendor/symfony/cache',
        'vendor/symfony/clock/Resources',
        'vendor/symfony/console/Attribute',
        'vendor/symfony/console/Command/InvokableCommand.php',
        'vendor/symfony/console/Command/TraceableCommand.php',
        'vendor/symfony/console/Completion',
        'vendor/symfony/console/DataCollector',
        'vendor/symfony/console/Helper/Table.php',
        'vendor/symfony/error-handler',
        'vendor/symfony/finder',
        'vendor/symfony/http-foundation/Session/Storage/Handler/IdentityMarshaller.php',
        'vendor/symfony/http-foundation/Session/Storage/Handler/MigratingSessionHandler.php',
        'vendor/symfony/http-kernel/DataCollector',
        'vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php',
        'vendor/symfony/http-kernel/Kernel.php',
        'vendor/symfony/mime/Crypto',
        'vendor/symfony/mime/HtmlToTextConverter/LeagueHtmlToMarkdownConverter.php',
        'vendor/symfony/mime/Part',
        'vendor/symfony/polyfill-intl-normalizer',
        'vendor/symfony/process',
        'vendor/symfony/string',
        'vendor/symfony/translation/Util/ArrayConverter.php',
        'vendor/symfony/var-dumper',
        'vendor/symfony/var-exporter',
        'vendor/symfony/translation/DataCollector',
        'vendor/openspout/openspout',
        'vendor/twig/twig',
        'vendor/tinywan/storage',
        'vendor/topthink/think-orm/stubs/load_stubs.php',
        'vendor/topthink/think-orm/src/db/Mongo.php',
        'vendor/topthink/think-orm/src/db/builder/Mongo.php',
        'vendor/topthink/think-orm/src/db/connector/Mongo.php',
        'vendor/topthink/think-orm/src/db/builder/Oracle.php',
        'vendor/topthink/think-orm/src/db/builder/Pgsql.php',
        'vendor/topthink/think-orm/src/db/builder/Sqlite.php',
        'vendor/topthink/think-orm/src/db/builder/Sqlsrv.php',
        'vendor/voku/portable-ascii',
        'vendor/webman/channel',
        'vendor/webman/console/src/Commands',
        'vendor/webman/console/src/Messages.php',
        'vendor/webman/console/src/Util.php',
        'vendor/webman/database/src/support/MongoModel.php',
        'vendor/webman/captcha/src/Font',
        'vendor/workerman/channel',
        'plugin/saiadmin/app/view',
        'plugin/saiadmin/public',
        'plugin/saiadmin/utils/code/stub',
        'vendor/illuminate/pagination/resources',
        'vendor/nesbot/carbon/src/Carbon/Lang',
        'vendor/nesbot/carbon/src/Carbon/List',
        'vendor/nesbot/carbon/src/Carbon/PHPStan',
        'vendor/symfony/error-handler/Resources',
        'vendor/symfony/console/DependencyInjection',
        'vendor/symfony/http-kernel/Resources',
        'vendor/symfony/polyfill-intl-idn/Resources',
        'vendor/symfony/polyfill-intl-normalizer/Resources',
        'vendor/symfony/polyfill-mbstring/Resources',
        'vendor/symfony/string/Resources',
        'vendor/symfony/translation/Resources',
        'vendor/symfony/var-dumper/Resources',
        'vendor/voku/portable-ascii/src/voku/helper/data',
        'vendor/zoujingli/ip2region/ip2region.xdb',
    ],
    // 编译排除项（动态文件与运行时资源；带 if 守卫的 helpers.php/functions.php 由
    // 打包命令自动平铺、coroutine 的 Context/WaitGroup/Barrier 由打包命令自动做
    // 静态属性可空化补丁、Worker/TcpConnection/AsyncTcpConnection/Select/File 由
    // 打包命令自动做可变参数闭包补丁，均在 .typephp/build/ 下生成 AOT 专用版本后参与编译）
    'ignore' => [
        'config',
        'public',
        'runtime',
        'app/view',
        'support/bootstrap.php',
        'vendor/autoload.php',
        'vendor/bin',
        'vendor/composer',
        'vendor/guzzlehttp/guzzle/src/functions_include.php',
        'vendor/workerman/webman-framework/src/support/helpers.php',
        'vendor/nikic/fast-route/src/functions.php',
        'vendor/workerman/webman-framework/src/support/bootstrap.php',
        'vendor/workerman/webman-framework/src/start.php',
        'vendor/workerman/webman-framework/src/windows.php',
        'vendor/workerman/webman-framework/src/Install.php',
        'vendor/nikic/fast-route/src/bootstrap.php',
        'vendor/nikic/fast-route/src/DataGenerator/CharCountBased.php',
        'vendor/nikic/fast-route/src/DataGenerator/GroupPosBased.php',
        'vendor/nikic/fast-route/src/DataGenerator/MarkBased.php',
        'vendor/nikic/fast-route/src/Dispatcher/CharCountBased.php',
        'vendor/nikic/fast-route/src/Dispatcher/GroupPosBased.php',
        'vendor/nikic/fast-route/src/Dispatcher/MarkBased.php',
        // Carbon installs these Doctrine adapters even when doctrine/dbal is absent.
        'vendor/carbonphp/carbon-doctrine-types',
        'vendor/illuminate/pagination/resources',
        'vendor/nelexa/zip/.php-cs-fixer.php',
        'vendor/nesbot/carbon/src/Carbon/Lang',
        'vendor/nesbot/carbon/src/Carbon/List',
        'vendor/saithink/saiadmin/src/orm',
        'vendor/saithink/saiadmin/src/plugin',
        'vendor/saithink/saipackage/src/plugin',
        'vendor/illuminate/bus/DynamoBatchRepository.php',
        'vendor/tinywan/jwt/src/config',
        'vendor/tinywan/jwt/tests',
        'vendor/tinywan/storage/.php-cs-fixer.php',
        'vendor/tinywan/storage/src/config',
        'vendor/tinywan/storage/tests',
        'vendor/tinywan/webman-typephp',
        'vendor/topthink/think-container/tests',
        'vendor/topthink/think-helper/tests',
        'vendor/topthink/think-orm/stubs/Facade.php',
        'vendor/symfony/error-handler/Resources',
        'vendor/symfony/event-dispatcher/Debug',
        'vendor/symfony/event-dispatcher/DependencyInjection',
        'vendor/symfony/http-kernel/Resources',
        'vendor/symfony/http-kernel/Bundle/BundleExtension.php',
        'vendor/symfony/http-kernel/DependencyInjection',
        'vendor/symfony/cache',
        'vendor/symfony/clock/Test',
        'vendor/symfony/console/Tester',
        'vendor/symfony/console/Attribute',
        'vendor/symfony/console/Command/InvokableCommand.php',
        'vendor/symfony/console/Command/TraceableCommand.php',
        'vendor/symfony/console/Completion',
        'vendor/symfony/console/DataCollector',
        'vendor/symfony/console/Helper/Table.php',
        'vendor/symfony/http-kernel/DataCollector',
        'vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php',
        'vendor/symfony/http-kernel/Kernel.php',
        'vendor/symfony/mime/HtmlToTextConverter/LeagueHtmlToMarkdownConverter.php',
        'vendor/symfony/translation/DataCollector',
        'vendor/symfony/cache/Traits/Relay',
        'vendor/symfony/cache/Traits/RelayProxy.php',
        'vendor/symfony/cache/Traits/RelayClusterProxy.php',
        'vendor/symfony/string/Resources',
        'vendor/symfony/translation/Resources',
        'vendor/symfony/var-dumper/Resources',
        'vendor/symfony/polyfill-intl-idn/Resources',
        'vendor/symfony/polyfill-intl-normalizer/Resources',
        'vendor/symfony/polyfill-mbstring/Resources',
        'vendor/symfony/polyfill-php80/Resources',
        'vendor/symfony/polyfill-php83/Resources',
        'vendor/symfony/polyfill-php84/Resources',
        'vendor/voku/portable-ascii/src/voku/helper/data',
        'vendor/symfony/polyfill-ctype/bootstrap.php',
        'vendor/symfony/polyfill-ctype/bootstrap80.php',
        'vendor/symfony/polyfill-intl-normalizer/bootstrap.php',
        'vendor/symfony/polyfill-mbstring/bootstrap.php',
        'vendor/symfony/polyfill-mbstring/bootstrap72.php',
        'vendor/symfony/polyfill-mbstring/bootstrap80.php',
        'vendor/symfony/polyfill-php80/bootstrap.php',
        'vendor/symfony/polyfill-php83/bootstrap.php',
        'vendor/symfony/polyfill-php83/bootstrap72.php',
        'vendor/symfony/polyfill-php83/bootstrap81.php',
        'vendor/symfony/polyfill-php84/bootstrap.php',
        'vendor/symfony/polyfill-php84/bootstrap72.php',
        'vendor/symfony/polyfill-php84/bootstrap82.php',
        'vendor/symfony/polyfill-php85/bootstrap80.php',
        'vendor/workerman/coroutine/src/Context.php',
        'vendor/workerman/coroutine/src/WaitGroup.php',
        'vendor/workerman/coroutine/src/Barrier.php',
        'vendor/workerman/coroutine/src/Barrier/BarrierInterface.php',
        'vendor/illuminate/bus/Batch.php',
        'vendor/illuminate/bus/ChainedBatch.php',
        'vendor/illuminate/database/Console',
        'vendor/illuminate/database/Eloquent/BroadcastableModelEventOccurred.php',
        'vendor/illuminate/database/Eloquent/BroadcastsEvents.php',
        'vendor/illuminate/database/Eloquent/BroadcastsEventsAfterCommit.php',
        'vendor/illuminate/events/CallQueuedListener.php',
        'vendor/illuminate/session/Console',
        'vendor/workerman/workerman/src/Worker.php',
        'vendor/workerman/workerman/src/Connection/TcpConnection.php',
        'vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php',
        'vendor/workerman/workerman/src/Events/Select.php',
        'vendor/workerman/webman-framework/src/File.php',
        'vendor/workerman/coroutine/tests',
        'vendor/workerman/channel/test',
        'vendor/workerman/crontab/example',
        'vendor/workerman/coroutine/stubs',
        'vendor/workerman/coroutine/src/Barrier/Swow.php',
        'vendor/workerman/coroutine/src/Channel/Swow.php',
        'vendor/workerman/coroutine/src/Context/Swow.php',
        'vendor/workerman/coroutine/src/Coroutine/Swow.php',
        'vendor/workerman/coroutine/src/WaitGroup/Swow.php',
        'vendor/workerman/workerman/src/Events/Swow.php',
        'vendor/workerman/coroutine/src/Barrier/Swoole.php',
        'vendor/workerman/coroutine/src/Channel/Swoole.php',
        'vendor/workerman/coroutine/src/Context/Swoole.php',
        'vendor/workerman/coroutine/src/Coroutine/Swoole.php',
        'vendor/workerman/coroutine/src/WaitGroup/Swoole.php',
        'vendor/workerman/workerman/src/Events/Swoole.php',
        'vendor/zoujingli/ip2region/_test.php',
    ],
];
